/** 设置页各字段：鼠标悬停（原生 title）显示的简短说明。 */
export const SETTINGS_FIELD_TIPS = {
  mode: "任务模式：development 为代码开发（<file>/<tool>）；philosophy 为思辨研究，通常要求 <thought>。",
  role: "本轮主 Agent 角色，决定系统提示词与行为边界（如 coder / philosopher）。",
  maxTurns: "单会话最多「思考—行动」循环次数；留空则沿用服务端 WORKFLOW_MAX_TURNS 或 .env。",
  interventionRoot:
    "根级干预秒数：>0 时在反思等节点挂起并弹窗等你输入「上帝指令」；与 workflow 内干预并存时，本值优先决定等待时长。",
  noSearch: "勾选则本次会话不向工具注册表挂载 web_search，避免外网请求。",
  noRag: "勾选则本次不挂载 RAG 向量检索/写入工具，避免加载向量库。",
  llmBaseUrl: "OpenAI 兼容 API 根地址，例如本机 Ollama 的 http://host:11434/v1。",
  llmApiKey: "HTTP 鉴权用密钥；Ollama 本地常为 ollama。仅随 WebSocket 发给本机后端。",
  llmModel: "主对话与（未单独指定时）护栏、摘要共用的模型名。",
  llmTimeout: "单次 chat 请求墙钟超时（秒），过大易占连接，过小易误杀长推理。",
  llmRetries: "超时或瞬态网络错误时的自动重试次数（不含首次）。",
  llmTemperature: "采样温度；代码任务宜偏低以提高格式稳定性。",
  summarizerModel: "上下文超长时摘要专用模型；留空则与主模型相同。",
  wfIvEnabled: "是否在 workflow 层开启干预逻辑（仍需 timeout>0 才会真正挂起）。",
  wfIvTimeout: "workflow 级干预挂起秒数；与根级干预二选一或叠加时以后端合并规则为准。",
  wfSensitive: "敏感工具名列表（逗号分隔）：调用前可触发干预挂起（需干预开启）。",
  wfMultiRoles: "额外参与 JSON 反思合并的角色（逗号分隔）；结论不一致会抛冲突。",
  wfGuardPre: "工具执行前：另开 LLM 会话尝试修正 <tool> 格式；失败则走可重试错误。",
  wfGuardOut: "出现完成标记但未跑工具时：另开 LLM 判断是否假完成；不通过则注入系统提示并继续。",
  wfGuardRounds: "每个护栏在放弃前最多调用修复模型的次数（1–5）。",
  wfGuardModel: "护栏专用模型；留空则与主模型相同。",
  ctxMaxTokens: "短期记忆 token 预算，超过会触发摘要压缩（需配置 summarizer）。",
  ctxPreserve: "压缩时保留的最近消息条数，越大越耗 token 但越不易丢细节。",
  ctxEncoding: "tiktoken 编码名，用于估算 token；与本地模型无强绑定，常用 cl100k_base。",
  exImage: "Docker 运行 Python 沙箱的基础镜像名，须本机已 docker pull / 构建。",
  exNamePrefix: "Executor 侧容器/资源名前缀，与 session 前缀可不同。",
  exWorkspace: "宿主机工作区目录（相对仓库根）；写入文件与挂载进容器均依赖此路径。",
  exMemory: "单容器内存上限，如 2g；过大可能挤占宿主机。",
  exCpu: "CPU 限额（逻辑核数比例或 Docker 语义），过大可能影响宿主机。",
  exTimeout: "单次在容器内执行脚本的默认墙钟超时（秒）。",
  sessPrefix: "session_id 与容器名使用的前缀，便于在 docker ps 中辨认。",
  sessIdle: "无 workflow 心跳时，超过该秒数自动回收容器。",
  sessHeartbeat: "workflow 每轮调用 heartbeat 的间隔参考；与空闲超时配合。",
} as const;
